### ISSUE TITLE
Fails to compile with VDR 2.6

### ISSUE THREAD

**Issue by M-Reimer** [vdr-projects/vdr-plugin-chanman#4]
Compile error:

```
chanman.cc: In member function ‘virtual void cSecondMenu::Move(int, int)’:
chanman.cc:788:60: error: invalid conversion from ‘cChannel*’ to ‘int’ [-fpermissive]
  788 |                                 cDevice::SetCurrentChannel(CurrentChannel);
      |                                                            ^~~~~~~~~~~~~~
      |                                                            |
      |                                                            cChannel*
In file included from /usr/include/vdr/dvbdevice.h:15,
                 from /usr/include/vdr/menuitems.h:14,
                 from /usr/include/vdr/plugin.h:14,
                 from chanman.cc:12:
/usr/include/vdr/device.h:366:37: note:   initializing argument 1 of ‘static void cDevice::SetCurrentChannel(int)’
  366 |   static void SetCurrentChannel(int ChannelNumber) { currentChannel = ChannelNumber; }
      |                                 ~~~~^~~~~~~~~~~~~
msgmerge -U --no-wrap --no-location --backup=none -q -N po/sv_SE.po po/chanman.pot
msgmerge -U --no-wrap --no-location --backup=none -q -N po/tr_TR.po po/chanman.pot
msgfmt -c -o po/ca_ES.mo po/ca_ES.po
make: *** [Makefile:60: chanman.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by M-Reimer** [comment]
Fixed in 0.0.13
